### ISSUE TITLE
token

### ISSUE THREAD

**Issue by mathisloge** [mapnik/gh-actions-test#1]
@artemp mhm. I'm getting `WARNING: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured` messages. 

Does the PAT have the `write:packages` permission?

**Comment by artemp** [comment]
@mathisloge I thought it did, hmm.. let me look into this again, perhaps I didn't do it correctly :smile:

**Comment by artemp** [comment]
@mathisloge Ok, `VCPKG_CACHE_PAT` should work now, let me know.

**Comment by mathisloge** [comment]
@artemp ah yes. Now it works! 😄
Thanks!

**Comment by mathisloge** [comment]
@artemp have you updated the PAT of `mapnik/mapnik`, too?

**Comment by artemp** [comment]
@mathisloge 
updated now ✅
